-- 旧テーブル削除
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS BKTB;
DROP TABLE IF EXISTS CPTB;
DROP TABLE IF EXISTS WDTB;
DROP TABLE IF EXISTS MARK;

-- USERテーブル
CREATE TABLE USER(
	USERID int AUTO_INCREMENT COMMENT "ユーザーID",
	EMLADR varchar(100) NOT NULL UNIQUE COMMENT "メールアドレス",
	PASSWD varchar(100) NOT NULL COMMENT "パスワード",
	ETDTTM timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "入力日時",
	PRIMARY KEY (USERID)
);


-- BKTBテーブル
CREATE TABLE BKTB(
    BOOKCD varchar(10) COMMENT "単語帳コード",
    BOOKNM varchar(100) NOT NULL UNIQUE COMMENT "単語帳名",
    ETDTTM timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "入力日時",
    PRIMARY KEY (BOOKCD)
);


-- CPTBテーブル
CREATE TABLE CPTB(
    CPTRCD varchar(10) COMMENT "チャプターコード",
    BOOKCD varchar(10) NOT NULL COMMENT "単語帳コード",
    CPTRNM varchar(100) NOT NULL COMMENT "チャプター名",
    ETDTTM timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "入力日時",
    PRIMARY KEY (CPTRCD),
    FOREIGN KEY (BOOKCD) REFERENCES BKTB(BOOKCD) ON DELETE CASCADE ON UPDATE CASCADE
);


-- WDTBテーブル
CREATE TABLE WDTB(
    WORDCD varchar(10) COMMENT "単語コード",
    CPTRCD varchar(10) NOT NULL COMMENT "チャプターコード",
    WORDNU int NOT NULL COMMENT "単語番号",
    WRDSPL varchar(100) NOT NULL COMMENT "単語スペル",
    WRDSND varchar(100) NOT NULL COMMENT "単語発音",
    ETDTTM timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "入力日時",
    PRIMARY KEY (WORDCD),
    FOREIGN KEY (CPTRCD) REFERENCES CPTB(CPTRCD) ON DELETE CASCADE ON UPDATE CASCADE
);

-- MARKテーブル
CREATE TABLE MARK(
	MARKID int AUTO_INCREMENT COMMENT "マークID",
	USERID int NOT NULL COMMENT "ユーザーID",
	WORDCD varchar(10) NOT NULL COMMENT "単語コード",
	CRRCTD boolean NOT NULL COMMENT "正解",
	ETDTTM timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "入力日時",
	PRIMARY KEY (MARKID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WORDCD) REFERENCES WDTB(WORDCD) ON DELETE CASCADE ON UPDATE CASCADE
);
